#!/usr/bin/env bash

set -e

echo "===== Centegix Zigbee Network Rebuild ====="

echo "Go to gateway directory"
cd /home/centegix/gateway || {
    echo "ERROR: Could not change directory to /home/centegix/gateway"
    exit 1
}
